name: Manage Spots
description: Add, update, delete spot on razmote-meteo
author: mbriot

inputs:
  issueBody:
    description: body of issue
    required: true
    default: 

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_ISSUE_BODY: ${{ inputs.issueBody }}
